name: Build and Deploy to azure

on: [push]

env:
  AZURE_AKS_CLUSTER: aksterminal
  AKS_RESOURCE_GROUP: terminal
  ACR_RESOURCE_URI: acrterminal.azurecr.io

jobs:
  build:
    name: tye deploy
    runs-on: ubuntu-latest
    steps:
    - uses: azure/deploy-to-aks@v1
      with:
        kubeconfig: '${{ secrets.KUBE_CONFIG}}' # Use secret (https://developer.github.com/actions/managing-workflows/storing-secrets/)
        #context: <context name>  #If left unspecified, current-context from kubeconfig is used as default
        
        container-registry-url: ${{ env.ACR_RESOURCE_URI }}
        container-registry-username: ${{ secrets.REGISTRY_USERNAME }}  # Use secret (https://developer.github.com/actions/managing-workflows/storing-secrets/)
        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}  # Use secret (https://developer.github.com/actions/managing-workflows/storing-secrets/)
    
