name: Docker Image CI / dockerhub

on: [push]


jobs:

  build_SecurityService:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        docker build . --file ./SecurityService/Dockerfile --tag osman0416/securityservice:latest
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        cd SecurityService
        docker push osman0416/securityservice:latest
  build_LoginService:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        docker build . --file ./LoginService/Dockerfile --tag osman0416/loginservice:latest
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        cd LoginService
        docker push osman0416/loginservice:latest
  build_ActivityService:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        docker build . --file ./ActivityService/Dockerfile --tag osman0416/activityservice:latest
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        cd ActivityService
        docker push osman0416/activityservice:latest
  build_ContainerService:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        docker build . --file ./ContainerService/Dockerfile --tag osman0416/containerservice:latest
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        cd ContainerService
        docker push osman0416/containerservice:latest


  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
      - name: Restore dependencies
        run: dotnet restore ./path/to/your.sln
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/dotnet@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  