name: Docker Image CI / dockerhub

on:
  push:
    branches: [ "main" ]


jobs:

  build_TweetService:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        docker build . --file ./SecuritysService/Dockerfile --tag osman0416/securityservice:latest
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        cd SecuritysService
        docker push osman0416/securityservice:latest