// <auto-generated />
using LoginService.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoginService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LoginService.models.Container", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Containers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContainerName = "727069e9-dae9-4c54-a9e0-6b5a87aa1e67",
                            Image = "alpine",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            ContainerName = "1d17cdf0-98f6-4ca9-b164-861994099a76",
                            Image = "ubuntu",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            ContainerName = "a4765804-ea33-4c47-a8c2-38bf47b7ac30",
                            Image = "debian",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            ContainerName = "92ee1493-216f-4b2e-9e0e-f23b660647e7",
                            Image = "fedora/memcached",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            ContainerName = "4b5e099f-ea50-41d1-8bf6-c9b34d13b1d3",
                            Image = "alpine",
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            ContainerName = "c64f9e6c-abc5-499a-9d9b-d8d691eb474a",
                            Image = "ubuntu",
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            ContainerName = "9fcfe6dc-ab67-46a1-ba4e-2302ac880402",
                            Image = "debian",
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            ContainerName = "89058d55-dec9-4375-8a34-6df302b75d43",
                            Image = "fedora/memcached",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("LoginService.models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "Password1",
                            Username = "User1"
                        },
                        new
                        {
                            Id = 2,
                            Password = "Password2",
                            Username = "User2"
                        });
                });

            modelBuilder.Entity("LoginService.models.Container", b =>
                {
                    b.HasOne("LoginService.models.User", null)
                        .WithMany("Containers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LoginService.models.User", b =>
                {
                    b.Navigation("Containers");
                });
#pragma warning restore 612, 618
        }
    }
}
